### ISSUE TITLE
nusmv

### ISSUE THREAD

**Issue by ShuaiQA** [EboYu/SmartHomeBench#1]
Hello, I read your article and would like to ask how you use the nusmv tool to detect situations like the duration of an action. I would be very grateful if you could share the CLOCK and TIMER modules.

**Comment by EboYu** [comment]
Thanks for your question. I attach some examples of CLOCK and TIMER modules used in our article as follows:

MODULE CLOCK
  VAR
    timer:0..1439;
  ASSIGN
    init(timer):=0;
    next(timer):=
      case
        timer=1439: 0;
        TRUE: timer+1;
      esac;

MODULE RUNIN(delay)
  VAR
    timer:0..500;
  ASSIGN
    init(timer):=0;
    next(timer):=
      case
        delay=0:0;
        timer=0 & delay>0: delay;
        timer>0 & delay>0: timer - 1;
        TRUE: timer;
      esac;
